#set_property IOSTANDARD DIFF_SSTL12 [get_ports ddr4_pl_sys_clk_p]
#set_property IOSTANDARD DIFF_SSTL12 [get_ports ddr4_pl_sys_clk_n]
#set_property PACKAGE_PIN AN21 [get_ports ddr4_pl_sys_clk_p]

set_property IOSTANDARD LVCMOS18 [get_ports FPGA_50MHz]
set_property PACKAGE_PIN AK33 [get_ports FPGA_50MHz]

set_property PACKAGE_PIN AE30 [get_ports gty_clk_n]
set_property PACKAGE_PIN AE29 [get_ports gty_clk_p]

## create clock
create_clock -period 6.734 -name gty_clk_n [get_ports gty_clk_n]
#create_clock -period 6.734 -name gty_clk_n [get_ports gty_clk_n]

create_clock -period 6.734 -name gty_clk_p [get_ports gty_clk_p]
#create_clock -period 6.734 -name gty_clk_p [get_ports gty_clk_p]

set_property IOSTANDARD LVCMOS33 [get_ports UART0_TXD]
set_property PACKAGE_PIN D5 [get_ports UART0_TXD]

set_property IOSTANDARD LVCMOS33 [get_ports UART0_RXD]
set_property PACKAGE_PIN D6 [get_ports UART0_RXD]

set_property IOSTANDARD LVCMOS33 [get_ports FAN_ON]
set_property PACKAGE_PIN F2 [get_ports FAN_ON]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]

set_property PACKAGE_PIN F4 [get_ports {LED[2]}]
set_property PACKAGE_PIN E3 [get_ports {LED[1]}]
set_property PACKAGE_PIN F3 [get_ports {LED[0]}]

set_property PACKAGE_PIN AU28 [get_ports REFCLK1_P]
set_property IOSTANDARD LVDS [get_ports REFCLK1_P]

set_property PACKAGE_PIN AW23 [get_ports REFCLK2_P]
set_property IOSTANDARD LVDS [get_ports REFCLK2_P]

set_property IOSTANDARD LVCMOS18 [get_ports PLL1_CSn]
set_property IOSTANDARD LVCMOS18 [get_ports PLL1_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports PLL1_SDO]
set_property IOSTANDARD LVCMOS18 [get_ports PLL1_SDIO]
set_property IOSTANDARD LVCMOS18 [get_ports PLL1_RSTn]
set_property IOSTANDARD LVCMOS18 [get_ports PLL1_PDNn]
set_property IOSTANDARD LVCMOS18 [get_ports PLL1_LOCK]
set_property IOSTANDARD LVCMOS18 [get_ports PLL1_OEn]
set_property IOSTANDARD LVCMOS18 [get_ports PLL1_SYNCn]

set_property PACKAGE_PIN AU30 [get_ports PLL1_CSn]
set_property PACKAGE_PIN AV30 [get_ports PLL1_SCLK]
set_property PACKAGE_PIN AV31 [get_ports PLL1_SDO]
set_property PACKAGE_PIN AW31 [get_ports PLL1_SDIO]
set_property PACKAGE_PIN AW33 [get_ports PLL1_RSTn]
set_property PACKAGE_PIN AT29 [get_ports PLL1_PDNn]
set_property PACKAGE_PIN AW28 [get_ports PLL1_LOCK]
set_property PACKAGE_PIN AT30 [get_ports PLL1_OEn]
set_property PACKAGE_PIN AW29 [get_ports PLL1_SYNCn]

set_property IOSTANDARD LVCMOS18 [get_ports PLL2_CSn]
set_property IOSTANDARD LVCMOS18 [get_ports PLL2_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports PLL2_SDO]
set_property IOSTANDARD LVCMOS18 [get_ports PLL2_SDIO]
set_property IOSTANDARD LVCMOS18 [get_ports PLL2_RSTn]
set_property IOSTANDARD LVCMOS18 [get_ports PLL2_PDNn]
set_property IOSTANDARD LVCMOS18 [get_ports PLL2_LOCK]
set_property IOSTANDARD LVCMOS18 [get_ports PLL2_OEn]
set_property IOSTANDARD LVCMOS18 [get_ports PLL2_SYNCn]

set_property PACKAGE_PIN AU24 [get_ports PLL2_CSn]
set_property PACKAGE_PIN AV27 [get_ports PLL2_SCLK]
set_property PACKAGE_PIN AU27 [get_ports PLL2_SDO]
set_property PACKAGE_PIN AT27 [get_ports PLL2_SDIO]
set_property PACKAGE_PIN AW26 [get_ports PLL2_RSTn]
set_property PACKAGE_PIN AV23 [get_ports PLL2_PDNn]
set_property PACKAGE_PIN AU23 [get_ports PLL2_LOCK]
set_property PACKAGE_PIN AU25 [get_ports PLL2_OEn]
set_property PACKAGE_PIN AT24 [get_ports PLL2_SYNCn]


set_property IOSTANDARD LVCMOS33 [get_ports RX_LOCKN]
set_property IOSTANDARD LVCMOS33 [get_ports RX_HPDN]
set_property IOSTANDARD LVCMOS33 [get_ports TX_LOCKN]
set_property IOSTANDARD LVCMOS33 [get_ports TX_HPDN]

set_property PACKAGE_PIN M14 [get_ports RX_LOCKN]
set_property PACKAGE_PIN L14 [get_ports RX_HPDN]
set_property PACKAGE_PIN H12 [get_ports TX_LOCKN]
set_property PACKAGE_PIN H10 [get_ports TX_HPDN]

#create_clock -period 20.000 -name freerun -waveform {0.000 10.000} [get_ports FPGA_50MHz]

set_property IOSTANDARD LVCMOS33 [get_ports {RX_DATA_FORMAT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_DATA_FORMAT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_OPTION[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_OPTION[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_OPTION[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_OPTION[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_OPTION[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_RSVD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_RSVD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_RSVD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_DATA_FORMAT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_DATA_FORMAT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_OPTION[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_OPTION[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_OPTION[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_OPTION[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_OPTION[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_RSVD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_RSVD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TX_RSVD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports RX_3D_EN]
set_property IOSTANDARD LVCMOS33 [get_ports RX_AC_DET]
set_property IOSTANDARD LVCMOS33 [get_ports RX_C_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports RX_C_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports RX_ERR_DET]
set_property IOSTANDARD LVCMOS33 [get_ports RX_QSMEN]
set_property IOSTANDARD LVCMOS33 [get_ports RX_RF_DONE]
set_property IOSTANDARD LVCMOS33 [get_ports RX_RO_BYPASS]
set_property IOSTANDARD LVCMOS33 [get_ports RX_RS_DONE]
set_property IOSTANDARD LVCMOS33 [get_ports RX_V_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports RX_V_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports RX_VX1_MODE]
set_property IOSTANDARD LVCMOS33 [get_ports RX_WP_IN]
set_property IOSTANDARD LVCMOS33 [get_ports TX_3D_EN]
set_property IOSTANDARD LVCMOS33 [get_ports TX_AC_DET]
set_property IOSTANDARD LVCMOS33 [get_ports TX_C_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports TX_C_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports TX_QSMEN]
set_property IOSTANDARD LVCMOS33 [get_ports TX_RO_BYPASS]
set_property IOSTANDARD LVCMOS33 [get_ports TX_V_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports TX_V_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports TX_VX1_MODE]
set_property IOSTANDARD LVCMOS33 [get_ports TX_WP_IN]

set_property PACKAGE_PIN K10 [get_ports RX_RO_BYPASS]
set_property PACKAGE_PIN K11 [get_ports RX_ERR_DET]
set_property PACKAGE_PIN L11 [get_ports RX_AC_DET]
set_property PACKAGE_PIN N12 [get_ports RX_3D_EN]
set_property PACKAGE_PIN M11 [get_ports RX_C_SCL]
set_property PACKAGE_PIN M10 [get_ports RX_C_SDA]
set_property PACKAGE_PIN N10 [get_ports {RX_DATA_FORMAT[0]}]
set_property PACKAGE_PIN M12 [get_ports {RX_DATA_FORMAT[1]}]
set_property PACKAGE_PIN R13 [get_ports {RX_OPTION[1]}]
set_property PACKAGE_PIN R14 [get_ports {RX_OPTION[2]}]
set_property PACKAGE_PIN P15 [get_ports {RX_OPTION[3]}]
set_property PACKAGE_PIN R15 [get_ports {RX_OPTION[4]}]
set_property PACKAGE_PIN J13 [get_ports {RX_OPTION[5]}]
set_property PACKAGE_PIN N14 [get_ports RX_QSMEN]
set_property PACKAGE_PIN N15 [get_ports RX_RF_DONE]
set_property PACKAGE_PIN L13 [get_ports {RX_RSVD[1]}]
set_property PACKAGE_PIN K13 [get_ports {RX_RSVD[2]}]
set_property PACKAGE_PIN P13 [get_ports {RX_RSVD[3]}]
set_property PACKAGE_PIN P10 [get_ports RX_V_SCL]
set_property PACKAGE_PIN P11 [get_ports RX_V_SDA]
set_property PACKAGE_PIN N13 [get_ports RX_VX1_MODE]
set_property PACKAGE_PIN P12 [get_ports RX_WP_IN]
set_property PACKAGE_PIN E11 [get_ports TX_3D_EN]
set_property PACKAGE_PIN B14 [get_ports TX_AC_DET]
set_property PACKAGE_PIN G11 [get_ports TX_C_SCL]
set_property PACKAGE_PIN F11 [get_ports TX_C_SDA]
set_property PACKAGE_PIN C13 [get_ports {TX_DATA_FORMAT[0]}]
set_property PACKAGE_PIN A14 [get_ports {TX_DATA_FORMAT[1]}]
set_property PACKAGE_PIN E13 [get_ports {TX_OPTION[1]}]
set_property PACKAGE_PIN D13 [get_ports {TX_OPTION[2]}]
set_property PACKAGE_PIN H13 [get_ports {TX_OPTION[3]}]
set_property PACKAGE_PIN J10 [get_ports {TX_OPTION[4]}]
set_property PACKAGE_PIN J11 [get_ports {TX_OPTION[5]}]
set_property PACKAGE_PIN F13 [get_ports TX_QSMEN]
set_property PACKAGE_PIN A13 [get_ports TX_RO_BYPASS]
set_property PACKAGE_PIN B12 [get_ports {TX_RSVD[1]}]
set_property PACKAGE_PIN A12 [get_ports {TX_RSVD[2]}]
set_property PACKAGE_PIN D12 [get_ports {TX_RSVD[3]}]
set_property PACKAGE_PIN G10 [get_ports TX_V_SCL]
set_property PACKAGE_PIN G12 [get_ports TX_V_SDA]
set_property PACKAGE_PIN C12 [get_ports TX_VX1_MODE]
set_property PACKAGE_PIN F12 [get_ports TX_WP_IN]
set_property PACKAGE_PIN L12 [get_ports RX_RS_DONE]

# IO Standard for gty_txpn_out

# output for gty transceiver serial output
set_property PACKAGE_PIN AF31 [get_ports gty_txp_out]
set_property PACKAGE_PIN AF32 [get_ports gty_txn_out]

#IO STANDARD for tmc_enc_init_out
set_property IOSTANDARD LVCMOS18 [get_ports tmc_enc_init_out]
# output for tmc_enc_init_out TP47
set_property PACKAGE_PIN AL27 [get_ports tmc_enc_init_out]




