
create_clock -period 20.000 -name freerun -waveform {0.000 10.000} [get_ports FPGA_50MHz]


set_clock_groups -asynchronous -group [get_clocks freerun]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins CPU_block/clk_wiz_1/inst/mmcme4_adv_inst/CLKOUT0]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {vx1_phy/vx1_phy/inst/gen_gtwizard_gthe4_top.vx1_phy_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[0].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/TXOUTCLK}]]

create_clock -period 5.934 -name clk_168_48 -add [get_nets clk_168_48]
create_clock -period 11.871 -name clk_84_24 -add [get_nets clk_84_24]
create_clock -period 11.871 -name rx_usrclk -add [get_nets rx_usrclk]

set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[17].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[17].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[31].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[31].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[24].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[24].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[1].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[1].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[23].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[23].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[2].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[2].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[9].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[9].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[16].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[16].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[22].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[22].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[27].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[27].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[26].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[26].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[18].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[18].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[25].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[25].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[0].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[0].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[19].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[19].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[30].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[30].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[5].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[5].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[12].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[12].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[29].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[29].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[20].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[20].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[4].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[4].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[21].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[21].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[28].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[28].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[3].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[3].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[10].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[10].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[15].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[15].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[14].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[14].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[11].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[11].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[8].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[8].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[7].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[7].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[13].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[13].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[6].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[6].Vbyone_Rx_Link_i/Rxphycon/add_counter_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[4].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[4].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[24].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[24].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[25].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[25].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[5].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[5].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[16].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[16].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[15].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[15].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[18].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[18].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[27].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[27].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[10].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[10].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[11].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[11].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[17].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[17].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[0].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[0].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[6].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[6].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[20].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[20].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[26].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[26].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[12].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[12].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[8].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[8].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[28].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[28].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[21].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[21].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[1].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[1].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[19].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[19].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[30].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[30].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[13].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[13].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[22].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[22].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[7].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[7].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[31].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[31].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/Reset_Blk/preset_shift_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/Reset_Blk/preset_shift_reg[3]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[14].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[14].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[2].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[2].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[9].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[9].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[3].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[3].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[29].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[29].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[23].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[0]}]
set_property ASYNC_REG true [get_cells {vx1_link/vx1_rx_link/r_loop[23].Vbyone_Rx_Link_i/Rxphycon/ext_lockn_cdc_reg[2]}]




